# Generated by Django 5.0.2 on 2024-02-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='amount',
            new_name='budget',
        ),
    ]
