# Generated by Django 5.0.2 on 2024-02-18 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
